### ISSUE TITLE
Improve the design quality 

### ISSUE THREAD

**Issue by Amin-Cheribet** [lotfio/silo#1]
i think it would be a better idea if a service locator is used instead of loading each component in a seperated method in silo/app/Http/Kernel.php
for example: 
```php
$locators = [
    'App/somepackage',
    'App/secondpackage',
    'App/Config'
];
```
while using a pipeline in silo/app/Http/Kernel.php to load them
```php
    public function load(Pipeline $pipeline)
    {
         foreach($locator as $locators) {
                $pipeline->pipe($locator);
         }
    }
```
and then just call the process method in the pipeline to do the job
```php
    $pipeline->process();
```

**Comment by lotfio** [comment]
Yep ! Sounds good.
